FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files first (for better caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port 5000 (non 5173 che è per Vite)
EXPOSE 5000

# Start server
CMD ["npm", "start"]
